# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - codeninjawebapp2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          cd NeighborlyFrontEnd
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip3 install azure-functions==1.2.1
          pip3 install certifi==2020.4.5.1
          pip3 install chardet==3.0.4
          pip3 install click==7.1.2
          pip3 install dominate==2.5.1
          pip3 install Flask==1.1.2
          pip3 install Flask-Bootstrap==3.3.7.1
          pip3 install idna==2.9
          pip3 install itsdangerous==1.1.0
          pip3 install Jinja2==2.11.2
          pip3 install MarkupSafe==1.1.1
          pip3 install requests==2.23.0
          pip3 install urllib3==1.25.9
          pip3 install visitor==0.1.3
          pip3 install Werkzeug==0.16.1
          pip3 install feedgen


      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'codeninjawebapp2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_497EC59756BB4261B3EF51ACD4E0FC89 }}
